package com.medcorp.lunar.database.dao;


import javax.annotation.PropertyKey;

import io.realm.RealmObject;

/**
 * Created by gaillysu on 15/11/17.
 */
public class UserDAO extends RealmObject {
    /**
     * field name and initialize value, Primary field
     */
    @PropertyKey
    private int id;


    /**
     * default age
     */
    private int age;

    /**
     * default weight, 75kg
     */
    private int weight;

    /**
     * default height, 175cm
     */
    private int height;

    /**
     * Sex = 0, female, sex = 1, male
     */
    private int sex;

    private long birthday;

    /**
     * first name
     */
    private String firstName;

    /**
     * last name
     */
    private String lastName;

    /**
     * created date,login date
     */
    private long createdDate;

    /**
     * remarks field, save extend user infomation, such as: blood type, email,step length...
     * it is a Json string
     */
    private String remarks;

    /**
     * this is generated by Nevo API when register
     */
    private String nevoUserID;

    /**
     * this is generated by Nevo API when register
     */
    private String nevoUserToken;
    private String nevoUserEmail;
    /**
     * this is generated by Validic API when create user
     */
    private String validicUserID;

    /**
     * this is generated by Validic API when create user
     */
    private String validicUserToken;
    private boolean nevoUserIsLogin;
    private String wechat;
    private boolean isConnectValidic;

    public UserDAO(){

    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public long getBirthday() {
        return birthday;
    }

    public void setBirthday(long birthday) {
        this.birthday = birthday;
    }

    public int getAge() {
        return age;
    }

    public void setAge(int age) {
        this.age = age;
    }

    public int getWeight() {
        return weight;
    }

    public void setWeight(int weight) {
        this.weight = weight;
    }

    public int getHeight() {
        return height;
    }

    public void setHeight(int height) {
        this.height = height;
    }

    public int getSex() {
        return sex;
    }

    public void setSex(int sex) {
        this.sex = sex;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public long getCreatedDate() {
        return createdDate;
    }

    public void setCreatedDate(long createdDate) {
        this.createdDate = createdDate;
    }

    public String getRemarks() {
        return remarks;
    }

    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    public String getNevoUserID() {
        return nevoUserID;
    }

    public void setNevoUserID(String nevoUserID) {
        this.nevoUserID = nevoUserID;
    }

    public String getNevoUserToken() {
        return nevoUserToken;
    }

    public void setNevoUserToken(String nevoUserToken) {
        this.nevoUserToken = nevoUserToken;
    }

    public String getNevoUserEmail() {
        return nevoUserEmail;
    }

    public void setNevoUserEmail(String nevoUserEmail) {
        this.nevoUserEmail = nevoUserEmail;
    }

    public String getValidicUserID() {
        return validicUserID;
    }

    public void setValidicUserID(String validicUserID) {
        this.validicUserID = validicUserID;
    }

    public String getValidicUserToken() {
        return validicUserToken;
    }

    public void setValidicUserToken(String validicUserToken) {
        this.validicUserToken = validicUserToken;
    }

    public boolean isNevoUserIsLogin() {
        return nevoUserIsLogin;
    }

    public void setNevoUserIsLogin(boolean nevoUserIsLogin) {
        this.nevoUserIsLogin = nevoUserIsLogin;
    }

    public String getWechat() {
        return wechat;
    }

    public void setWechat(String wechat) {
        this.wechat = wechat;
    }

    public boolean isConnectValidic() {
        return isConnectValidic;
    }

    public void setConnectValidic(boolean connectValidic) {
        isConnectValidic = connectValidic;
    }


}
