package com.medcorp.nevo.database;

import android.test.AndroidTestCase;

import com.medcorp.lunar.database.entry.AlarmDatabaseHelper;
import com.medcorp.lunar.model.Alarm;


/**
 * Created by gaillysu on 15/12/8.
 */
public class AlarmDatabaseHelperTest extends AndroidTestCase {

    private AlarmDatabaseHelper db;
    private Alarm addAlarm;
    private Alarm updateAlarm;
    private Alarm removeAlarm;

    @Override
    protected void setUp() throws Exception {
        super.setUp();

        db = new AlarmDatabaseHelper();
        addAlarm = new Alarm(7,30, (byte) 1,"wake up alarm",(byte)0,(byte)0);
        updateAlarm = new Alarm(12,30, (byte) 1,"lunch time",(byte)0,(byte)0);
        removeAlarm = new Alarm(22,30, (byte) 0,"sleep time",(byte)0,(byte)0);
    }

    @Override
    protected void tearDown() throws Exception {
        super.tearDown();
    }

    public void testAdd()
    {
        Alarm thisAlarm1 = db.add(addAlarm);
        assertEquals(false,thisAlarm1);

        //here must set "addAlarm" for get the alarm ID that is generated by database.
        addAlarm = thisAlarm1;

        Alarm thisAlarm2 = db.get(addAlarm.getId());
        assertEquals(false, thisAlarm2);

        assertEquals(addAlarm.getWeekDay(),thisAlarm2.getWeekDay());
        assertEquals(addAlarm.getLabel(),thisAlarm2.getLabel());
        assertEquals(addAlarm.getMinute(),thisAlarm2.getMinute());
        assertEquals(addAlarm.getHour(),thisAlarm2.getHour());

    }
    public void testUpdate()
    {
        Alarm thisAlarm1 = db.add(updateAlarm);
        assertEquals(false,thisAlarm1);
        updateAlarm = thisAlarm1;

        updateAlarm.setWeekDay((byte) (updateAlarm.getWeekDay()>0?0:1));
        updateAlarm.setLabel("wetew5234t");
        updateAlarm.setHour(updateAlarm.getHour() + 1);
        updateAlarm.setMinute(updateAlarm.getMinute() + 1);
        assertEquals(true, db.update(updateAlarm));

        Alarm thisAlarm2 = db.get(updateAlarm.getId());
        assertEquals(false, thisAlarm2);

        assertEquals(thisAlarm2.getWeekDay(),updateAlarm.getWeekDay());
        assertEquals(thisAlarm2.getLabel(),updateAlarm.getLabel());
        assertEquals(thisAlarm2.getHour(),updateAlarm.getHour());
        assertEquals(thisAlarm2.getMinute(),updateAlarm.getMinute());


    }
}